/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110463-g129c7bf53f-20230502"
#endif /* AVUTIL_FFVERSION_H */
